import React from "react";
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import {DataTable} from "primereact/datatable";
import {Column} from "primereact/column";

const Pflanzen_Uebersicht = () => {

    const pflanzen = [
        {Pflanze: "Basilikum", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Dill", PH_MIN: "5", PH_MAX: "6,5"},
        {Pflanze: "Majoran", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Oregano", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Petersilie", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Pfefferminze", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Rosmarin", PH_MIN: "5", PH_MAX: "6"},
        {Pflanze: "Salbei", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Thymian", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Artischocke", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Aubergine", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Blumenkohl", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Bohnen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Brokkoli", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Brunnenkresse", PH_MIN: "5,5", PH_MAX: "7,5"},
        {Pflanze: "Chicoree", PH_MIN: "5", PH_MAX: "6,5"},
        {Pflanze: "Chili (Peperoni)", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Chinakohl", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Endivien", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Erbsen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Feldsalat", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Fenchel", PH_MIN: "5", PH_MAX: "6"},
        {Pflanze: "Grünkohl", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Gurken", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Ingwer", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Kartoffeln", PH_MIN: "5", PH_MAX: "7"},
        {Pflanze: "Knoblauch", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Kohlrabi", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Kopfsalat", PH_MIN: "5,5", PH_MAX: "7,5"},
        {Pflanze: "Kürbis", PH_MIN: "5,5", PH_MAX: "7,5"},
        {Pflanze: "Kresse", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Mais", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Mangold", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Möhren", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Pak Choi", PH_MIN: "6,5", PH_MAX: "7"},
        {Pflanze: "Paprika", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Porree", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Radicchio", PH_MIN: "6", PH_MAX: "6,8"},
        {Pflanze: "Radieschen & Rettich", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Rosenkohl", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Rote Bete", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Schalotten", PH_MIN: "5,5", PH_MAX: "7,5"},
        {Pflanze: "Schnittlauch", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Schwarzwurzeln", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Spargel", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Spinat", PH_MIN: "5,5", PH_MAX: "7,5"},
        {Pflanze: "Sellerie", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Steckrübe", PH_MIN: "6,8", PH_MAX: "7,5"},
        {Pflanze: "Süßkartoffel", PH_MIN: "5,5", PH_MAX: "6"},
        {Pflanze: "Tomaten", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Weißkohl, Rotkohl & Wirsing", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Winterrettich", PH_MIN: "5", PH_MAX: "6,5"},
        {Pflanze: "Zucchini", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Zwiebeln", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Äpfel", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Aprikosen", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Birnen", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Erdbeeren", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Heidelbeeren und Preiselbeeren", PH_MIN: "4,5", PH_MAX: "6,5"},
        {Pflanze: "Himbeeren & Brombeeren", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Blaubeere", PH_MIN: "4", PH_MAX: "5,5"},
        {Pflanze: "Johannisbeeren (schwarz & weiß)", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Johannisbeeren rot", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Pfirsich", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Pflaumen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Rhabarber", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Sauerkirschen", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Stachelbeere amerikanisch", PH_MIN: "5", PH_MAX: "6,5"},
        {Pflanze: "Stachelbeere europäisch", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Süßkirschen", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Quitten", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Weinreben", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Haselnuss", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Walnuss", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Eiben", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Fichten & Tannen", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Kiefer & Lärchen", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Lebensbäume (Thuja)", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Wacholder", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Weymouthskiefer", PH_MIN: "4,5", PH_MAX: "6"},
        {Pflanze: "Zeder weiß", PH_MIN: "4,5", PH_MAX: "5,5"},
        {Pflanze: "Zeder virginisch", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Zypressen", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Ahorn", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Birke", PH_MIN: "5", PH_MAX: "6"},
        {Pflanze: "Buche", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Eiche", PH_MIN: "5", PH_MAX: "6"},
        {Pflanze: "Flieder", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Forsythie", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Kastanie", PH_MIN: "5", PH_MAX: "6"},
        {Pflanze: "Liguster", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Linde", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Magnolie", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Pappel", PH_MIN: "5,5", PH_MAX: "7,5"},
        {Pflanze: "Platane", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Robinie", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Rose", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Trauerweide", PH_MIN: "5", PH_MAX: "6"},
        {Pflanze: "Weide", PH_MIN: "5,5", PH_MAX: "7,5"},
        {Pflanze: "Abelien", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Akazie", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Adonisröschen", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Akelei", PH_MIN: "6,5", PH_MAX: "8,5"},
        {Pflanze: "Alpenveilchen", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Alpen-Edelweiß", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Amaryllis", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Amerikanische Pampasgras", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Anemonen", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Arnika", PH_MIN: "5", PH_MAX: "6,5"},
        {Pflanze: "Astern", PH_MIN: "5", PH_MAX: "7"},
        {Pflanze: "Azaleen", PH_MIN: "4", PH_MAX: "5,5"},
        {Pflanze: "Ballonblume", PH_MIN: "6", PH_MAX: "6,5"},
        {Pflanze: "Begonien", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Bergenien", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Berglorbeer", PH_MIN: "4,5", PH_MAX: "6"},
        {Pflanze: "Besenheide", PH_MIN: "4", PH_MAX: "6"},
        {Pflanze: "Blaukissen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Blausterne", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Bleiwurz", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Bougainvillea", PH_MIN: "5,5", PH_MAX: "7,5"},
        {Pflanze: "Brandschopf", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Braunellen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Bromelien", PH_MIN: "5", PH_MAX: "6"},
        {Pflanze: "Bubikopf", PH_MIN: "5", PH_MAX: "6"},
        {Pflanze: "Buchsbaum", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Christusdorn", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Chrysantheme", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Cineraria", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Cistus", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Clarkia", PH_MIN: "6", PH_MAX: "6,5"},
        {Pflanze: "Coleus", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Convolvulus", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Chrysanthemen", PH_MIN: "6,5", PH_MAX: "6,8"},
        {Pflanze: "Clematis", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Dahlien", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Dreimasterblumen", PH_MIN: "5", PH_MAX: "6"},
        {Pflanze: "Ehrenpreis", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Efeu", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Eibisch", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Europäische Pfeifenstrauch", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Erika", PH_MIN: "4,5", PH_MAX: "6,5"},
        {Pflanze: "Farne", PH_MIN: "4,5", PH_MAX: "5,5"},
        {Pflanze: "Fetthennen", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Fingerhirse", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Flamingoblumen", PH_MIN: "5", PH_MAX: "6"},
        {Pflanze: "Flammenblumen", PH_MIN: "5", PH_MAX: "6,5"},
        {Pflanze: "Fleißige Lieschen", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Flockenblumen", PH_MIN: "5", PH_MAX: "6,5"},
        {Pflanze: "Forsythien", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Fuchsien", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Gardenien", PH_MIN: "5", PH_MAX: "6"},
        {Pflanze: "Gazanien", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Gänseblümchen", PH_MIN: "6,5", PH_MAX: "7"},
        {Pflanze: "Geranien", PH_MIN: "5,5", PH_MAX: "6"},
        {Pflanze: "Ginster", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Gipskräuter", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Glockenblumen", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Goldregen", PH_MIN: "6.0", PH_MAX: "7.0"},
        {Pflanze: "Goldruten", PH_MIN: "5", PH_MAX: "7"},
        {Pflanze: "Grüne Minze", PH_MIN: "5,5", PH_MAX: "7,5"},
        {Pflanze: "Günsel", PH_MIN: "4", PH_MAX: "6"},
        {Pflanze: "Gladiolen", PH_MIN: "6,5", PH_MAX: "7"},
        {Pflanze: "Heidekraut", PH_MIN: "4,5", PH_MAX: "6"},
        {Pflanze: "Hibiskus", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Hornkräuter", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Hortensien", PH_MIN: "4", PH_MAX: "4,5"},
        {Pflanze: "Hyazinthen", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Iris", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Jasmin", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Kamelie", PH_MIN: "4", PH_MAX: "5,5"},
        {Pflanze: "Klivie", PH_MIN: "6,5", PH_MAX: "7"},
        {Pflanze: "Kokardenblumen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Kornblumen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Köcherblümchen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Krokusse", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Lilien", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Löwenmäulchen", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Lupinen", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Maiglöckchen", PH_MIN: "4,5", PH_MAX: "6"},
        {Pflanze: "Moos", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Narzissen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Nelken", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Nieswurz", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Ochsenzungen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Oleander", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Orchideen", PH_MIN: "4,5", PH_MAX: "5,5"},
        {Pflanze: "Osterglocken", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Osterlilien", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Pantoffelblumen", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Passionsblumen", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Petunien", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Pfingstrosen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Prärielilien", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Primeln", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Quitte", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Rhododendron", PH_MIN: "4", PH_MAX: "5,5"},
        {Pflanze: "Ringelblume", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Raps", PH_MIN: "6,5", PH_MAX: "7,5"},
        {Pflanze: "Rittersporn", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Rosen", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Schleifenblumen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Schneeglöckchen", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Schwertlilien", PH_MIN: "5", PH_MAX: "6,5"},
        {Pflanze: "Sonnenblumen", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Sonnenwenden", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Steinbrech", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Steckrosen", PH_MIN: "6", PH_MAX: "8"},
        {Pflanze: "Stiefmütterchen", PH_MIN: "5,5", PH_MAX: "7"},
        {Pflanze: "Strauchmargerite", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Studentenblume", PH_MIN: "5", PH_MAX: "7,5"},
        {Pflanze: "Sukkulenten", PH_MIN: "5", PH_MAX: "6,5"},
        {Pflanze: "Tamarisken", PH_MIN: "6,5", PH_MAX: "8"},
        {Pflanze: "Tränendes Herz", PH_MIN: "6", PH_MAX: "7,5"},
        {Pflanze: "Tulpen", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Usambaraveilchen", PH_MIN: "4,5", PH_MAX: "5,5"},
        {Pflanze: "Veilchen", PH_MIN: "5,5", PH_MAX: "6,5"},
        {Pflanze: "Vergißmeinnicht", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Wachsblume", PH_MIN: "6,5", PH_MAX: "7"},
        {Pflanze: "Waldmeister", PH_MIN: "4", PH_MAX: "6"},
        {Pflanze: "Weihnachtskaktus", PH_MIN: "5", PH_MAX: "6"},
        {Pflanze: "Zierspargel", PH_MIN: "6", PH_MAX: "7"},
        {Pflanze: "Zinnien", PH_MIN: "5,5", PH_MAX: "7,5"}
    ]


    return (
        <div className="flex flex-column card-container green-container row-gap-3 text-justify">
            <DataTable value={pflanzen}>
                <Column field={"Pflanze"} header="Pflanze" filter filterPlaceholder="Suche"/>
                <Column field={"PH_MIN"} header="PH-Min" sortable/>
                <Column field={"PH_MAX"} header="PH-Max" sortable/>
            </DataTable>

        </div>)
};

export default Pflanzen_Uebersicht;
